version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: indexer
      MONGO_INITDB_ROOT_PASSWORD: indexer
      MONGO_INITDB_DATABASE: indexer
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: indexer
      ME_CONFIG_MONGODB_ADMINPASSWORD: indexer
      ME_CONFIG_MONGODB_URL: mongodb://indexer:indexer@mongo:27017/

volumes:
  data: