version: '3'
services:
  app:
    image: indexer-backend
    environment:
      DB_HOST: database
      DB_USERNAME: indexer
      DB_PASSWORD: indexer
      DB_DATABASE: indexer
      DB_PORT: 5432
    ports:
      - "8080:8080"

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: indexer
      POSTGRES_USER: indexer
      POSTGRES_PASSWORD: indexer
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: