version: '3'
services:
  app:
    image: indexer-backend
    environment:
      DB_HOST: mongo
      DB_USERNAME: indexer
      DB_PASSWORD: indexer
      DB_DATABASE: indexer
      DB_PORT: 27017
    ports:
      - 8080:8080

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: indexer
      MONGO_INITDB_ROOT_PASSWORD: indexer
      MONGO_INITDB_DATABASE: indexer
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: indexer
      ME_CONFIG_MONGODB_ADMINPASSWORD: indexer
      ME_CONFIG_MONGODB_URL: mongodb://indexer:indexer@mongo:27017/

volumes:
  data: