spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: indexer
      password: indexer
      database: indexer
server:
  servlet:
    context-path: /api
logging:
  level:
    root: info

