spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:indexer}
    username: ${DB_USERNAME:indexer}
    password: ${DB_PASSWORD:indexer}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: info
serpapi:
  key1: ${SERP_KEY1}
cache:
  barcode:
    override: true
    ttl: 30d

