spring:
  data:
    mongodb:
      authentication-database: admin
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      username: ${DB_USERNAME:indexer}
      password: ${DB_PASSWORD:indexer}
      database: ${DB_DATABASE:indexer}
server:
  servlet:
    context-path: /api
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: info

