spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: indexer
      password: indexer
      database: indexer
server:
  servlet:
    context-path: /api
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: info

