spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:indexer}
    username: ${DB_USERNAME:indexer}
    password: ${DB_PASSWORD:indexer}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    context-path: /api
  error:
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root: info
serpapi:
  key1: ${SERP_KEY1:empty_placeholder}
cache:
  barcode:
    override: true
    ttl: 30d
springdoc:
  swagger-ui:
    path: "/docs"
firebase:
  token:
    remove:
      days: 30d

mail:
  address: ${MAIL_ADDRESS}
  alias: "Indexer"
  password: ${MAIL_PASSWORD}
  smtp:
    auth: true
    host: ${MAIL_HOST}
    default-host: "smtp.gmail.com"
    port: 587
    starttls:
      enable: true

notification:
  days-num: 5
  time: "0 54 13 * * *"